name: compile and push on the registry

on:
  push:
    branches: develop

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push Docker image
        run: |
          DATE=$(date +"%d%m%Y")
          docker buildx build --push --tag ghcr.io/${{github.repository_owner }}/final:$DATE --tag ghcr.io/${{github.repository_owner }}/front:latest .